### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by Tiago138** [pangolindex/components#482]
After I updated to the latest version I get the error

Module not found: Can't resolve '@pangolindex/governance/artifacts/contracts/GovernorAlpha.sol/GovernorAlpha.json'

The previous version I was using

"@pangolindex/components": "6.0.2",
"@pangolindex/sdk": "5.0.1",

**Comment by prodesert22** [comment]
Please use components version `7.3.5` and sdk version `5.3.2`

**Comment by Tiago138** [comment]
> Please use components version `7.3.5` and sdk version `5.3.2`

I our application we was using version 6, now after updating to version 7.3.5 i started getting the module not found error
```
Module not found: Can't resolve '@pangolindex/governance/artifacts/contracts/GovernorAlpha.sol/GovernorAlpha.json'
```

**Comment by prodesert22** [comment]
so, please add `@pangolindex/governance` version  `1.2.0`

**Comment by Tiago138** [comment]
> 

I add it but it seems there is still something missing, now I am getting the error.
Error: Invariant failed: Invalid key NETWORK

**Comment by prodesert22** [comment]
Now you need to wrap you app with this 

```ts
// main.tsx
import { createWeb3ReactRoot, Web3ReactProvider } from '@web3-react/core';
import { NetworkContextName} from '@pangolindex/components';
import { Web3Provider } from '@ethersproject/providers';

const Web3ProviderNetwork = createWeb3ReactRoot(NetworkContextName);

function getLibrary(provider: any): Web3Provider {
  try {
    const library = new Web3Provider(provider, 'any')
    library.pollingInterval = 15000
    return library
  } catch (error) {
    return provider
  }
}


ReactDOM.render(
  <StrictMode>
    <Web3ReactProvider getLibrary={getLibrary}>
      <Web3ProviderNetwork getLibrary={getLibrary}>
        <App />
      </Web3ProviderNetwork>
    </Web3ReactProvider>
  </StrictMode>,
  document.getElementById('root')
);
```

**Comment by Tiago138** [comment]
> 

It worked, but I had to left it like this, next is just giving errors importing NetworkContextName
```
const Web3ProviderNetwork =
  typeof window !== 'undefined' && createWeb3ReactRoot('NETWORK')
```

**Comment by prodesert22** [comment]
Hey @Tiago138 you have more issue, if no I will close this issue as resolved, we improve your docs about how to install and use in these prs

https://github.com/pangolindex/components/pull/485
https://github.com/pangolindex/components/pull/486

**Comment by Tiago138** [comment]
I don't have any more issues, you can close it, thanks.
